import CTAButton from '@/ui/cta-button';
import Link from 'next/link';

export default function ZoolyAIPage() {
  return (
    <div className="container mx-auto py-8">
      <div className="max-w-4xl mx-auto px-4">
        <h1 className="text-4xl font-bold text-white mb-6">Zooly AI</h1>

        <div className="flex items-center text-gray-400 mb-8">
          <span className="mr-4">2024 - 2025</span>
          <span className="mr-4">•</span>
          <span>Sr. Web Developer & Voice Synthesis Lead</span>
          <span className="mx-4">•</span>
          <Link
            href="https://zooly.ai"
            target="_blank"
            rel="noopener noreferrer"
            className="text-purple-400 hover:text-purple-300 transition-colors inline-flex items-center gap-2"
          >
            <span>zooly.ai</span>
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
            </svg>
          </Link>
        </div>

        <div className="prose prose-lg prose-invert max-w-none">
          <p className="text-gray-300">
            I was initially hired at Zooly AI as a Senior Web Developer, leveraging my extensive experience with React, JavaScript, TailwindCSS, and AWS services (including Lambda, S3, and more). However, after the team discovered my machine learning expertise, my role quickly evolved.
          </p>

          <h2 className="text-2xl font-semibold text-white mt-8 mb-4">Voice Synthesis Leadership</h2>
          <p className="text-gray-300">
            I was appointed to lead the voice synthesis teams, where I built and trained sophisticated voice models and datasets to replicate the voices of several high-profile celebrities, including:
          </p>

          <div className="grid grid-cols-2 gap-4 my-6">
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <span className="text-purple-300">• Snoop Dogg</span>
            </div>
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <span className="text-purple-300">• 50 Cent</span>
            </div>
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <span className="text-purple-300">• Cardi B</span>
            </div>
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <span className="text-purple-300">• Bailey Zimmerman</span>
            </div>
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <span className="text-purple-300">• Donald Trump</span>
            </div>
            <div className="bg-gray-800/50 p-4 rounded-lg">
              <span className="text-purple-300">• Dr. Dre</span>
            </div>
          </div>

          <h2 className="text-2xl font-semibold text-white mt-8 mb-4">Innovative Testing: "AI or Not?"</h2>
          <p className="text-gray-300">
            I pioneered a novel approach to test our voice models in an unbiased way. The system, which I called "AI or Not?", presented users with various audio samples and challenged them to determine whether each sample was generated by AI or was an authentic recording.
          </p>

          <p className="text-gray-300 mt-4">
            The effectiveness of our models was demonstrated when Snoop Dogg's wife was unable to distinguish between our AI-generated voice and her husband's actual recordings—a testament to the exceptional quality of our voice synthesis technology.
          </p>

          <p className="text-gray-300 mt-4">
            I implemented a sophisticated feedback system that collected user responses from the "AI or Not?" tests and fed this data directly back into our training pipeline. This continuous improvement loop allowed us to systematically identify and eliminate audio artifacts that were giving away the AI-generated nature of our samples, resulting in increasingly natural-sounding voice synthesis.
          </p>

          <div className="bg-purple-900/30 p-5 rounded-lg border border-purple-500/30 my-8">
            <h3 className="text-xl font-semibold text-white mb-3">Technical Innovations</h3>
            <ul className="space-y-3">
              <li className="flex items-start gap-3">
                <svg className="w-6 h-6 text-purple-400 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <span className="text-gray-200">Feedback loop system that fed user test results back into the model for continuous improvement</span>
              </li>
              <li className="flex items-start gap-3">
                <svg className="w-6 h-6 text-purple-400 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <span className="text-gray-200">Fine-tuning methodology to systematically eliminate audio artifacts</span>
              </li>
              <li className="flex items-start gap-3">
                <svg className="w-6 h-6 text-purple-400 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                <span className="text-gray-200">Custom "tuning" system for ElevenLabs integration to enhance model performance</span>
              </li>
            </ul>
          </div>

          <h2 className="text-2xl font-semibold text-white mt-8 mb-4">ElevenLabs Integration Enhancement</h2>
          <p className="text-gray-300">
            I developed a specialized "tuning" system that significantly improved our integration with ElevenLabs' voice synthesis platform. This custom solution allowed us to optimize the input parameters and post-processing techniques, resulting in voice outputs that surpassed the quality of standard ElevenLabs implementations. The system included:
          </p>

          <ul className="list-disc pl-6 space-y-2 text-gray-300 mt-4">
            <li>Parameter optimization algorithms that automatically adjusted settings based on voice characteristics</li>
            <li>Custom post-processing filters to enhance naturalness and eliminate common synthesis artifacts</li>
            <li>Voice-specific tuning profiles that maximized the quality for each celebrity voice model</li>
          </ul>

          <p className="text-gray-300 mt-4">
            After a productive year at Zooly AI, I decided to resign from my position. I continue to wish the team the best of luck in their future endeavors and innovations in the AI space.
          </p>
        </div>

        <div className="mt-12">
          <CTAButton href="/contact" color="purple">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
            </svg>
            <span>CONTACT ME</span>
          </CTAButton>
        </div>
      </div>
    </div>
  );
}
